### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by iahun** [Airr/MBC#1]
I'm using MSYS2. g++ gives this error:

```
$ g++ mbc4.cc -o mbc
mbc4.cc:26:10: fatal error: sys/wait.h: No such file or directory
   26 | #include <sys/wait.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

I read mbc4.cc and found various Linux-only headers. I'm seeking a version of BCX doesn't use the Windows API headers and I was suggested to this repo on the BCX forum. Could you add support for Windows/MSYS2?

**Comment by Airr** [comment]
To be honest, this was never implemented with Windows in mind, only Linux and macOS were targeted.

With MSYS2, you might find the header in /usr/include/sys, which might not be in the MSYS include path by default.

I think you'll find the the effort to essentially re-port this back to Windows will require a lot of work.

**Comment by iahun** [comment]
> To be honest, this was never implemented with Windows in mind, only Linux and macOS were targeted.
> 
> With MSYS2, you might find the header in /usr/include/sys, which might not be in the MSYS include path by default.
> 
> I think you'll find that the effort to essentially re-port this back to Windows will require a lot of work.

You just give me good pointer. This code needs a POSIX compatible environment. I will only have to use MSYS Core instead of MSYS MinGW64. All of the POSIX headers are available there. This is the only problem left that you could help:

```
$ g++ -Wformat -D_FORTIFY_SOURCE=2 -Wno-write-strings mbc4.cc -o mbc4
mbc4.cc: In function ‘void CloseAll()’:
mbc4.cc:5162:3: error: ‘fcloseall’ was not declared in this scope; did you mean ‘_fcloseall’?
 5162 |   fcloseall();
      |   ^~~~~~~~~
      |   _fcloseall
```

**Comment by iahun** [comment]
Update: no porting needed, with this command it compiled out of the box on MSYS2 Core:

`$ g++ -Wformat -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -Wno-write-strings mbc4.cc -o mbc4`

@Airr You could add this into readme.
